# Allow Firebase client-side credentials
# These are public by design and protected by Firebase security rules
paths-ignore:
  - '**/firebase-credentials.ts'
  - '**/firebaseConfig.ts'
  - '**/firebase.config.ts'
